config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  } 
  root 'home#index'
   
  resources :groups, only: [:index, :show, :new, :create] do
    resources :entities, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :group_entities
  has_many :groups, through: :group_entities

  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_entities
  has_many :entities, through: :group_entities

  validates :name, presence: true
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities
  has_many :groups

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group

  def new
    @entity = Entity.new
    @groups = current_user.groups.all
  end

  def create
    @entity = @group.entities.new(entity_params.merge(user_id: current_user.id))
    params[:entity][:group_ids]

    if @entity.save
      group_ids = params[:entity][:group_ids]
      redirect_to group_ids.present? ? group_path(group_ids.first) : groups_path,
                  notice: 'Transaction created successfully.'
    else
      render 'new'
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups.all
  end

  def new
    @group = current_user.groups.new
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to groups_path, notice: 'Category created successfully.'
    else
      render 'new'
    end
  end

  def show
    @group = current_user.groups.find(params[:id])
    @entities = @group.entities
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/entities/new.html.erb
<div class="phone-border">
  <div class="flex-column align-items-centerd-flex flex-column align-items-center" style="min-height: 70vh; padding-bottom: 10vh; max-width: 100%!important;">
   <%= form_with(model: [@group, @entity], url: group_entities_path(@group)) do |form| %>
      <!-- Barra superior azul -->
      <div class="w-100 bg-primary text-white text-center d-flex justify-content-between align-items-center" style="height: 50px;">
        <%= link_to groups_path, class: "text-white ml-3" do %>
          <i class="fas fa-arrow-left" style="margin-left: 5px;"></i>
        <% end %>
        <span>NEW TRANSACTION</span>
        <%= form.submit "Save", class: "text-white mr-3 bg-transparent border-0", style: "cursor: pointer;" %>
      </div>
      <div class="w-100 mt-auto mb-auto" style="max-width: 100%!important;">
        <div class="form-group">
          <%= form.text_field :name, autofocus: true, class: "form-control", placeholder: "transaction" %>
        </div>
        <div class="form-group">
          <%= form.number_field :amount, class: "form-control", placeholder: "Amount" %>
        </div>
        <div class="form-group custom-dropdown">
          <label for="category-select" class="control-label">Select Category</label>
          <div class="options">
            <label for="category-select" class="control-label">Select Category</label>
            <div class="options">
              <%= select_tag 'entity[group_ids]', options_for_select(@groups.map { |g| [g.name, g.id] }, Array(@entity.try(:group_ids))), id: 'group_select', class: "form-control", multiple: true %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/groups/index.html.erb
<div class="phone-border" style="position: relative;">
  <div class="d-flex flex-column align-items-center" style="min-height: 70vh; padding-bottom: 10vh; max-width: 100%!important;">

   <div class="w-100 bg-primary text-white text-center d-flex justify-content-between align-items-center" style="height: 50px;">
      <%= link_to groups_path, class: "text-white ml-3" do %>
        <i class="fas fa-arrow-left" style="margin-left: 5px;"></i>
      <% end %>
      <span>CATEGORIES</span>
      <%= link_to 'New', new_group_path, class: "text-white", style: "margin-right: 5px; text-decoration: none; color: inherit;" %>

    </div>

     <div class="w-100" style="flex-grow: 1; max-width: 100%!important;">
      <ul class="list-unstyled">
     <% @groups.each do |group| %>
  <li class="bg-light p-3 my-2 shadow d-flex">
    <% if group.present? %> <!-- Add this line to check if group is present -->
      <%= link_to group_path(group), class: "w-100 d-flex align-items-center", style: "text-decoration: none; color: inherit;" do %>
        <div style="width: 25%;">
          <%= image_tag(group.icon) %>
        </div>
        <div style="width: 50%;">
          <%= group.name %>
        </div>
      <% end %>
    <% end %>
  </li>
<% end %>
      </ul>
    </div>

<div style="position: absolute; bottom: 0; left: 0; width: 100%; display: flex; align-items: center; justify-content: center; height: 50px; background-color: #5fb523;">
  <%= link_to 'Create new category', new_group_path, class: "btn btn-success", style: "color: white; border: 1px solid white; background-color: #5fb523;" %>
</div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="phone-border">
  <div class="flex-column align-items-centerd-flex flex-column align-items-center" style="min-height: 70vh; padding-bottom: 10vh; max-width: 100%!important;">
    <%= form_with(model: @group) do |form| %>
      <div class="w-100 bg-primary text-white text-center d-flex justify-content-between align-items-center" style="height: 50px;">
<%= link_to groups_path, class: "text-white ml-3" do %>
  <i class="fas fa-arrow-left" style="margin-left: 5px;"></i>
<% end %>
        <span>CATEGORY</span>
        <%= form.submit "Save", class: "text-white mr-3 bg-transparent border-0", style: "cursor: pointer;" %>
      </div>

      <div class="w-100 mt-auto mb-auto" style="max-width: 100%!important;">
        <div class="form-group">
          <%= form.text_field :name, autofocus: true, class: "form-control", placeholder: "Name of the category" %>
        </div>

<%= form_with model: @group do |form| %>
  <div class="icon-selection">
    <div class="icon-header">
      <%= form.label :icon, "Select an Icon" %>
    </div>
    <div class="icon-options">
      <%= form.radio_button :icon, "icon1.png", id: "icon1", class: "d-none" %>
      <%= label_tag "icon1", image_tag("icon1.png"), class: "icon-label" %>

      <%= form.radio_button :icon, "icon2.png", id: "icon2", class: "d-none" %>
      <%= label_tag "icon2", image_tag("icon2.png"), class: "icon-label" %>

      <%= form.radio_button :icon, "icon3.png", id: "icon3", class: "d-none" %>
      <%= label_tag "icon3", image_tag("icon3.png"), class: "icon-label" %>

      <%= form.radio_button :icon, "icon4.png", id: "icon4", class: "d-none" %>
      <%= label_tag "icon4", image_tag("icon4.png"), class: "icon-label" %>

      <%= form.radio_button :icon, "icon5.png", id: "icon5", class: "d-none" %>
      <%= label_tag "icon5", image_tag("icon5.png"), class: "icon-label" %>



    </div>
  </div>
<% end %>

      </div>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="phone-border" style="position: relative;">
  <div class="d-flex flex-column align-items-center" style="min-height: 70vh; padding-bottom: 10vh; max-width: 100%!important;">

   <div class="w-100 bg-primary text-white text-center d-flex justify-content-between align-items-center" style="height: 50px;">
      <%= link_to groups_path, class: "text-white ml-3" do %>
        <i class="fas fa-arrow-left" style="margin-left: 5px;"></i>
      <% end %>
      <span>TRANSACTIONS</span>
      <%= link_to 'New', new_group_entity_path(@group), class: "text-white", style: "margin-right: 5px; text-decoration: none; color: inherit;" %>
    </div>

    <div class="w-100 d-flex my-2 shadow bg-white">
      <div style="width: 25%;">
        <%= image_tag(@group.icon) %>
      </div>
      <div style="width: 50%;">
        <%= @group.name %>
      </div>
      <div style="width: 25%;">
        <%= @group.entities.sum(:amount) %>
      </div>
    </div>

    <div class="w-100 mt-3" style="flex-grow: 1; max-width: 100%!important;">
      <ul class="list-unstyled">
        <% @group.entities.each do |entity| %>
          <li class="bg-light p-3 my-2 shadow d-flex">
            <div style="width: 75%;">
              <%= entity.name %><br>
<span style="font-size: 0.5em;"><%= entity.created_at.strftime("%Y-%m-%d %H:%M") %></span>

            </div>
            <div style="width: 25%;">
              <%= entity.amount %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

    <div style="position: absolute; bottom: 0; left: 0; width: 100%; display: flex; align-items: center; justify-content: center; height: 50px; background-color: #5fb523;">
      <%= link_to 'New Transaction', new_group_entity_path(@group), class: "btn btn-success", style: "color: white; border: 1px solid white; background-color: #5fb523;" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class ="phone-border">
  <div class="container d-flex flex-column align-items-center bg-green" style="min-height: 70vh; padding-bottom: 10vh; ">
    <div class="text-center w-100 mb-auto" style="max-width: 400px;">
      <h1 class="mt-0 mb-5 text-primary">Money Manger</h1>
        <%= image_tag("logo.png", class: "img-fluid") %>
      <h3 class ="mt-0 mb-5 ">Budget Brilliance, Simplified.<h3>
      <p class="mt-0 mb-5 bg-secondary text-danger" > Expense Mastery Made Easy with Our App! </p>
    </div>
    
    <div class="w-100 d-flex flex-column align-items-center mt-auto">
      <% if user_signed_in? %>
        <%= form_with url: destroy_user_session_path, method: :delete do %>
          <%= submit_tag 'Logout', class: "btn btn-primary w-100" %>
        <% end %>
      <% else %>
        <div class="w-100">
          <%= link_to "LOG IN", new_user_session_path, class: "btn btn-primary w-100", style: "background-color: #3778c2; color: white;" %>
        </div>
        <div class="w-100 mt-2">
          <%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-outline-dark w-100", style: "color: #434b54; border-color: #434b54;" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>